Repository equinor/template-fastapi-react, pull requests merged in 2022-11, with the labels that each got.

#104 fix: resolve PR feedback from #97
  api/src/app.py
  api/src/tests/unit/data_providers/repositories/test_TodoRepository.py
  api/src/tests/unit/features/todo/use_cases/test_update_todo.py
  api/src/tests/yarn.lock
  web/src/api/generated/api.ts
  web/src/api/generated/api/health-check-api.ts
  web/src/api/generated/api/todos-api.ts
  web/src/api/generated/api/whoami-api.ts
  web/src/api/generated/base.ts
  web/src/api/generated/common.ts
  web/src/api/generated/configuration.ts
  web/src/api/generated/index.ts
  web/src/api/generated/models/add-todo-request.ts
  web/src/api/generated/models/add-todo-response.ts
  web/src/api/generated/models/delete-todo-by-id-response.ts
  web/src/api/generated/models/error-response.ts
  web/src/api/generated/models/get-todo-all-response.ts
  web/src/api/generated/models/get-todo-by-id-response.ts
  web/src/api/generated/models/update-todo-request.ts
  web/src/api/generated/models/update-todo-response.ts
  web/src/common/components/Header.tsx
Labels: type: :sparkles: enhancement

#120 fix (cicd): use correct branch name (`master` => `main`)
  .github/workflows/codeql.yml
  .github/workflows/publish.yaml
Labels: status: :no_entry_sign: invalid, type: :ship: ci

#122 build: fix mac m1 virtiofs docker problem
  docker-compose.override.yml
Labels: type: :hammer: build
